import streamlit as st
import requests
import os

# ==========================================
# 1. CONFIGURATION & NETWORKING
# ==========================================
st.set_page_config(page_title="Financial RAG Assistant", page_icon="📈", layout="centered")

# Use environment variables for the backend URL (Critical for AWS deployment)
# Locally, it defaults to localhost. On AWS, you will set BACKEND_URL in docker-compose.
BACKEND_HOST = os.getenv("BACKEND_URL", "http://localhost:8001")
ASK_URL = f"{BACKEND_HOST}/ask"
FEEDBACK_URL = f"{BACKEND_HOST}/feedback"

# =  =

st.title("📈 Wall Street AI Analyst")
st.caption("Advanced Financial RAG Engine powered by Groq & Gemini")

# ==========================================
# 2. SESSION STATE INITIALIZATION
# ==========================================
if "messages" not in st.session_state:
    st.session_state.messages = []

# ==========================================
# 3. CHAT INTERFACE
# ==========================================
# Display previous chat messages
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# User Input
if prompt := st.chat_input("E.g., Compare Apple's R&D spending to its total revenue"):
    
    # Add user message to UI and state
    with st.chat_message("user"):
        st.markdown(prompt)
    st.session_state.messages.append({"role": "user", "content": prompt})

    # Call FastAPI Backend
    with st.chat_message("assistant"):
        message_placeholder = st.empty()
        
        with st.spinner("Analyzing SEC Filings & Cross-Referencing..."):
            try:
                payload = {
                    "query": prompt,
                    "ticker": "AAPL", # Defaults to Apple
                    "top_k": 5
                }
                
                response = requests.post(ASK_URL, json=payload, timeout=30)
                
                if response.status_code == 200:
                    data = response.json()
                    answer = data["answer"]
                    query_hash = data.get("query_hash")
                    is_cached = data.get("cached", False)
                    provider = data.get("provider", "Unknown")
                    sources = data.get("sources", [])

                    # 1. Render main answer
                    message_placeholder.markdown(answer)
                    
                    # 2. Technical Metadata (Recruiter-facing "Wow" factor)
                    if is_cached:
                        st.caption("⚡ **Semantic Cache Hit:** Response served instantly from PostgreSQL.")
                    else:
                        st.caption(f"🤖 **Live Inference:** Generated by {provider}")

                    # 3. Document Citations
                    if sources:
                        with st.expander("📚 View Source Context & Reranker Scores"):
                            for i, src in enumerate(sources):
                                st.markdown(f"**Source {i+1} | {src.get('document_type', 'SEC Filing')}**")
                                st.write(src.get('text', ''))
                                st.progress(src.get('score', 0.0), text=f"Relevance Score: {src.get('score', 0.0):.4f}")
                                st.divider()

                    # 4. Professional Feedback Loop
                    if query_hash:
                        st.write("---")
                        st.write("Rate this analysis:")
                        # Prevent duplicate voting
                        if f"voted_{query_hash}" not in st.session_state:
                            c1, c2, _ = st.columns([1, 1, 10])
                            with c1:
                                if st.button("👍", key=f"up_{query_hash}"):
                                    requests.post(FEEDBACK_URL, json={"query_hash": query_hash, "rating": 1})
                                    st.session_state[f"voted_{query_hash}"] = True
                                    st.toast("Feedback recorded!")
                                    st.rerun()
                            with c2:
                                if st.button("👎", key=f"down_{query_hash}"):
                                    requests.post(FEEDBACK_URL, json={"query_hash": query_hash, "rating": -1})
                                    st.session_state[f"voted_{query_hash}"] = True
                                    st.toast("Logged for review.")
                                    st.rerun()
                        else:
                            st.caption("Thank you for your feedback! ⭐")

                    # Save to session history
                    st.session_state.messages.append({"role": "assistant", "content": answer})

                else:
                    st.error(f"Backend Error ({response.status_code}): {response.text}")

            except requests.exceptions.ConnectionError:
                st.error("🚨 Connection Failed: Ensure your FastAPI backend is running and the URL is correct.")
            except Exception as e:
                st.error(f"An unexpected error occurred: {e}")