"""init

Revision ID: 26bc97b42bb7
Revises: 
Create Date: 2026-03-01 16:58:48.886022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26bc97b42bb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_hash', sa.String(), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('llm_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_cache_id'), 'semantic_cache', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_cache_query_hash'), 'semantic_cache', ['query_hash'], unique=True)
    op.create_index(op.f('ix_semantic_cache_ticker'), 'semantic_cache', ['ticker'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_hash', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedback_id'), 'user_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_user_feedback_query_hash'), 'user_feedback', ['query_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedback_query_hash'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_semantic_cache_ticker'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_query_hash'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_id'), table_name='semantic_cache')
    op.drop_table('semantic_cache')
    # ### end Alembic commands ###
